//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataLayer
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class sargujaNewsEntities : DbContext
    {
        public sargujaNewsEntities()
            : base("name=sargujaNewsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NEWS_Advertise> NEWS_Advertise { get; set; }
        public virtual DbSet<NEWS_Category> NEWS_Category { get; set; }
        public virtual DbSet<NEWS_News> NEWS_News { get; set; }
        public virtual DbSet<NEWS_NewsTag> NEWS_NewsTag { get; set; }
        public virtual DbSet<NEWS_User> NEWS_User { get; set; }
    
        public virtual ObjectResult<USP_GetCategoryPageContents_Result> USP_GetCategoryPageContents(string newCategory)
        {
            var newCategoryParameter = newCategory != null ?
                new ObjectParameter("NewCategory", newCategory) :
                new ObjectParameter("NewCategory", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetCategoryPageContents_Result>("USP_GetCategoryPageContents", newCategoryParameter);
        }
    
        public virtual ObjectResult<USP_GetFrontPageContents_Result> USP_GetFrontPageContents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetFrontPageContents_Result>("USP_GetFrontPageContents");
        }
    
        public virtual ObjectResult<USP_GetTagPageContents_Result> USP_GetTagPageContents(string tagName)
        {
            var tagNameParameter = tagName != null ?
                new ObjectParameter("TagName", tagName) :
                new ObjectParameter("TagName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<USP_GetTagPageContents_Result>("USP_GetTagPageContents", tagNameParameter);
        }
    }
}
